
demo_color_printer: main.cc color-printer.hh
	g++ -g3 -std=c++11 -o demo_color_printer main.cc


demo_ej14: Ejercicio14.cc color-printer.hh
	g++ -g3 -std=c++11 -o demo_ej14 Ejercicio14.cc

demo_ej15: Ejercicio15.cc color-printer.hh
	g++ -g3 -std=c++11 -o demo_ej15 Ejercicio15.cc

clean:
	rm -f demo_*

.PHONY: clean